# Generated by Django 5.2.3 on 2025-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_income_source_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Bills', 'Bills'), ('Other', 'Other'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment'), ('Gift', 'Gift'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Bills', 'Bills'), ('Other', 'Other'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment'), ('Gift', 'Gift'), ('Other', 'Other')], max_length=100),
        ),
    ]
